### PR TITLE
Added fan modes

### PR DESCRIPTION
**Pull request by nprez83**
# Proposed Changes

> Added fan modes to be able to implement fan control in main integration

## Checklist

- [ ] Change has been tested and works on my device(s).

[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/

### CODE REVIEW

**Review by timmo001 — APPROVED** [review]

**Comment by nprez83** [comment]
Quick question @timmo001, I was trying to test the code changes I've made to the climate.py file in my lyric integration to enable fan control, but I'm still getting the error stating LyricDevice does not have a fan property, which is what this PR should have accomplished. I'm still new to pull requests etc. so just wondering how to go about getting my updated climate.py to access the updated aiolyric. Thanks in advance.

**Comment by nprez83** [comment]
Hi @amokrunner, I had the code ready to go, but wasn't able to implement it as the aiolyric version hadn't been yet bumped to include the changes above, so the properties associated with fan modes were not yet available for lyric objects. Not sure if the aiolyric version has gotten bumped to this yet or not. Here are the changes I had ready to implement. Happy to throw in a PR once we confirm that the aiolyric version has been updated. I looked at the changelogs for 2022.4-6 and did not see that change listed.

1) Add the following flags to the climate.const import statemenet: 
    ATTR_FAN_MODE,
    FAN_AUTO,
    FAN_ON,
    FAN_DIFFUSE,
    SUPPORT_FAN_MODE,

2) Add SUPPORT_FAN_MODE flag to SUPPORT_FLAGS_LCC definition

3) Add the following code after the HVAC_ACTIONS definition: 

LYRIC_FAN_AUTO = "Auto"
LYRIC_FAN_ON = "On"
LYRIC_FAN_CIRCULATE = "Circulate"

LYRIC_FAN_MODES = {
    FAN_AUTO: LYRIC_FAN_AUTO,
    FAN_ON: LYRIC_FAN_ON,
    FAN_DIFFUSE: LYRIC_FAN_CIRCULATE,
}

FAN_MODES = {
    LYRIC_FAN_AUTO: FAN_AUTO,
    LYRIC_FAN_ON: FAN_ON,
    LYRIC_FAN_CIRCULATE: FAN_DIFFUSE,
}

4) Add the following code within the __init__

        # Setup supported fan modes
        if LYRIC_FAN_AUTO in device.fan.allowedModes:
            self._fan_modes.append(FAN_AUTO)

        if LYRIC_FAN_ON in device.fan.allowedModes:
            self._fan_modes.append(FAN_ON)

        if LYRIC_FAN_CIRCULATE in device.fan.allowedModes:
            self._fan_modes.append(FAN_DIFFUSE)"""

5) Add the following properties: 

    @property
    def fan_mode(self) -> str:
        """Return the hvac mode."""
        return FAN_MODES[self.device.fan.changeableValues.mode]

    @property
    def fan_modes(self) -> list[str]:
        """List of available fan modes."""
        return self._fan_modes

6) Lastly, define async_set_fan_mode: 

    async def async_set_fan_mode(self, fan_mode: str) -> None:
        """Set fan mode."""
        _LOGGER.debug("Fan mode from frontend: %s", fan_mode)
        _LOGGER.debug("Fan mode passed to lyric: %s", LYRIC_FAN_MODES[fan_mode])
        try:
            await self._update_fan(
                self.location,
                self.device,
                mode=LYRIC_FAN_MODES[fan_mode]
            )
        except LYRIC_EXCEPTIONS as exception:
            _LOGGER.error(exception)
        await self.coordinator.async_refresh()

**Comment by nprez83** [comment]
I just saw that 2022.7 comes with python 3.10, which I believe will have the updated version of aiolyric, including the changes related to fan modes. Once that happens I'll test out the changes I delineated above and will submit a PR.

**Comment by smcpeck** [comment]
@nprez83 I just started poking at this same thing for HA and then stumbled upon your comments here... and movement/guidance on this?

**Pull request merged**
